import { type NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";

import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Bird</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Bird
          </h1>
          <div className="flex flex-col items-center gap-2">
            <p className="text-2xl text-white">
              Press to fetch GOOG stock data
            </p>
            <TickerShowCase />
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;

const TickerShowCase: React.FC = () => {
  const { data, isFetching, refetch } = trpc.candles.getByTicker.useQuery({ ticker: "GOOG" }, { enabled: false});

  if (data) {
    console.log(data)
  }

  return (
    <div className="flex flex-col items-center justify-center gap-4 mt-4">
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={() => refetch()}
      >
        {isFetching ? "Fetching.." : "Fetch"}
      </button>
      <p className="text-center text text-white">
        {data && "See console for data."}
      </p>
    </div>
  );
};

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = trpc.auth.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined },
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => signOut() : () => signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};
